EXTRA_CFLAGS += -Iarch/arm/mach-msm

 
ifeq ($(TARGET_PRODUCT),lge_univa_q)
obj-$(CONFIG_MACH_MSM8X55_UNIVA_Q) += board-univaq.o
obj-$(CONFIG_MACH_MSM8X55_UNIVA_Q) += board-univaq-pm.o
obj-$(CONFIG_MACH_MSM8X55_UNIVA_Q) += board-univaq-sound.o
obj-$(CONFIG_MACH_MSM8X55_UNIVA_Q) += board-univaq-misc.o
obj-$(CONFIG_MACH_MSM8X55_UNIVA_Q) += board-univaq-mmc.o
obj-$(CONFIG_MACH_MSM8X55_UNIVA_Q) += board-univaq-input.o

 
# obj-$(CONFIG_MACH_MSM8X55_UNIVA_Q) += board-victor-panel.o
obj-$(CONFIG_MACH_MSM8X55_UNIVA_Q) += board-univaq-panel.o
 

obj-$(CONFIG_MACH_MSM8X55_UNIVA_Q) += board-univaq-bt.o
obj-$(CONFIG_MACH_MSM8X55_UNIVA_Q) += board-univaq-camera.o

obj-$(CONFIG_MACH_LGE) += devices_lge.o

obj-$(CONFIG_LGE_HEADSET_MAX14579) += lge_headset_MAX14579.o
obj-$(CONFIG_LGE_PROC_COMM) += lge_proc_comm.o
obj-y += lge_audio_misc_ctrl.o

obj-$(CONFIG_LGE_SUPPORT_AT_CMD) += lge_ats.o
obj-$(CONFIG_LGE_SUPPORT_AT_CMD) += lge_ats_cmd.o
obj-$(CONFIG_LGE_SUPPORT_AT_CMD) += lge_ats_eta.o
obj-$(CONFIG_LGE_SUPPORT_AT_CMD) += lge_ats_mmc.o
obj-$(CONFIG_LGE_SUPPORT_AT_CMD) += lge_ats_event_log.o
obj-$(CONFIG_LGE_SUPPORT_AT_CMD) += lge_ats_flex.o  

obj-$(CONFIG_LGE_HANDLE_PANIC) += lge_handle_panic.o
obj-$(CONFIG_LGE_ATCMD_TTY) += lge_tty_atcmd.o
obj-$(CONFIG_LGE_FACTORY_PATCH) += lge_temp.o

endif

ifeq ($(TARGET_PRODUCT),lge_flip)
obj-$(CONFIG_MACH_MSM8X55_FLIP) += board-flip.o
obj-$(CONFIG_MACH_MSM8X55_FLIP) += board-flip-pm.o
obj-$(CONFIG_MACH_MSM8X55_FLIP) += board-flip-sound.o
obj-$(CONFIG_MACH_MSM8X55_FLIP) += board-flip-misc.o
obj-$(CONFIG_MACH_MSM8X55_FLIP) += board-flip-mmc.o
obj-$(CONFIG_MACH_MSM8X55_FLIP) += board-flip-input.o
obj-$(CONFIG_MACH_MSM8X55_FLIP) += board-flip-panel.o

obj-$(CONFIG_MACH_MSM8X55_FLIP) += board-flip-bt.o
obj-$(CONFIG_MACH_MSM8X55_FLIP) += board-flip-camera.o

obj-$(CONFIG_MACH_LGE) += devices_lge.o

obj-$(CONFIG_LGE_HEADSET_MAX14579) += lge_headset_MAX14579.o
obj-$(CONFIG_LGE_PROC_COMM) += lge_proc_comm.o
obj-$(CONFIG_MACH_MSM8X55_FLIP) += lge_audio_misc_ctrl.o

obj-$(CONFIG_LGE_SUPPORT_AT_CMD) += lge_ats.o
obj-$(CONFIG_LGE_SUPPORT_AT_CMD) += lge_ats_cmd.o
obj-$(CONFIG_LGE_SUPPORT_AT_CMD) += lge_ats_eta.o
obj-$(CONFIG_LGE_SUPPORT_AT_CMD) += lge_ats_mmc.o
obj-$(CONFIG_LGE_SUPPORT_AT_CMD) += lge_ats_event_log.o
obj-$(CONFIG_LGE_SUPPORT_AT_CMD) += lge_ats_flex.o  
obj-$(CONFIG_LGE_HANDLE_PANIC) += lge_handle_panic.o
obj-$(CONFIG_LGE_ATCMD_TTY) += lge_tty_atcmd.o
obj-$(CONFIG_LGE_FACTORY_PATCH) += lge_temp.o

endif

ifeq ($(TARGET_PRODUCT),lge_victor)
xxxx kernel make file error point2. (victor)

obj-$(CONFIG_MACH_MSM8X55_VICTOR) += board-victor.o
obj-$(CONFIG_MACH_MSM8X55_VICTOR) += board-victor-pm.o
obj-$(CONFIG_MACH_MSM8X55_VICTOR) += board-victor-sound.o
obj-$(CONFIG_MACH_MSM8X55_VICTOR) += board-victor-misc.o
obj-$(CONFIG_MACH_MSM8X55_VICTOR) += board-victor-mmc.o
obj-$(CONFIG_MACH_MSM8X55_VICTOR) += board-victor-input.o
obj-$(CONFIG_MACH_MSM8X55_VICTOR) += board-victor-panel.o
obj-$(CONFIG_MACH_MSM8X55_VICTOR) += board-victor-bt.o
obj-$(CONFIG_MACH_MSM8X55_VICTOR) += board-victor-camera.o

obj-$(CONFIG_MACH_LGE) += devices_lge.o

obj-$(CONFIG_LGE_HEADSET_MAX14579) += lge_headset_MAX14579.o
obj-$(CONFIG_LGE_PROC_COMM) += lge_proc_comm.o

obj-$(CONFIG_LGE_SUPPORT_AT_CMD) += lge_ats.o
obj-$(CONFIG_LGE_SUPPORT_AT_CMD) += lge_ats_cmd.o
obj-$(CONFIG_LGE_SUPPORT_AT_CMD) += lge_ats_eta.o
obj-$(CONFIG_LGE_SUPPORT_AT_CMD) += lge_ats_mmc.o
obj-$(CONFIG_LGE_SUPPORT_AT_CMD) += lge_ats_event_log.o
obj-$(CONFIG_LGE_SUPPORT_AT_CMD) += lge_ats_flex.o  

obj-$(CONFIG_LGE_HANDLE_PANIC) += lge_handle_panic.o
obj-$(CONFIG_LGE_ATCMD_TTY) += lge_tty_atcmd.o

endif
 

